#!/usr/bin/python3
""" resolve digits in file into an outcome of two prime num """
import sys


def factorize():
    """ Func finds file and resolve digits provided into two prime num """
    try:
        file = sys.argv[1]
        with open(file) as f:
            for line_number in f:
                line_number = int(line_number)
                if line_number % 2 == 0:
                    print("{}={}*{}".format(line_number, line_number // 2, 2))
                        continue
                u = 3
                while u < line_number // 2:
                    if line_number % u == 0:
                        print("{}={}*{}".format(line_number, line_number // u, u))
                        break
                    u = u + 2
                if u == (line_number // 2) + 1:
                    print("{}={}*{}".format(line_number, line_number, 1))
    except (IndexError):
        pass


factorize()
